version: 0.2

phases:
  pre_build:
    commands:
      - echo Installing dependencies...
      - npm ci --only=production
  build:
    commands:
      - echo Building application...
      - npm run build
  post_build:
    commands:
      - echo Build completed successfully

artifacts:
  files:
    - '**/*'
  exclude-paths:
    - node_modules/aws-sdk/**
    - .git/**
    - test/**
    - coverage/**
